### ISSUE TITLE
库中找不到这个方法：org-roam-node-backlink-count 

### ISSUE THREAD

**Issue by iT-Boyer** [cheerio-pixel/.emacs.d#1]
库中找不到这个方法`org-roam-node-backlink-count`，方便分享一下吗？
```elisp
(cl-defmethod org-roam-node-backlinkcount ((node org-roam-node))
+    (format "[%d]" (org-roam-node-backlink-count node)))
```

**Comment by cheerio-pixel** [comment]
Sorry but I don't understand Chinese, but I did my best to translate it. Under what I understand you want the `org-roam-node-backlink-count` function? Well, that function is actually a getter that is generated by the `org-roam-node` struct, defined in file `elisp/org-roam-patch.el`. Actually, in that file you can see how I set that field in the database and how I patch the org roam functions to count backlinks with the `mymy-org-roam-get-backlinks` each time there is update or creation.
